// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiBih0UUNhsaGtfLKBmO1gruxffKEtsZc',
    appId: '1:458231053874:web:640b5dee428de9f2cec62b',
    messagingSenderId: '458231053874',
    projectId: 'flutter-64a39',
    authDomain: 'flutter-64a39.firebaseapp.com',
    storageBucket: 'flutter-64a39.firebasestorage.app',
    measurementId: 'G-TL3YJ8D53J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAvcbC_lDbK-LZQxdxSb8iIbD_ss8GKjE',
    appId: '1:458231053874:android:ffc2110e626639b1cec62b',
    messagingSenderId: '458231053874',
    projectId: 'flutter-64a39',
    storageBucket: 'flutter-64a39.firebasestorage.app',
  );
}
